"""add settings table

Revision ID: 51a458eecafa
Revises: 
Create Date: 2026-09-23 05:04:28.810734

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '51a458eecafa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_delivery_dashboard_settings',
    sa.Column('shot_status_task_type_id', sa.String(length=36), nullable=True),
    sa.Column('delivered_status_ids', sa.JSON(), nullable=False),
    sa.Column('retake_status_ids', sa.JSON(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugin_delivery_dashboard_settings')
    # ### end Alembic commands ###
